#! /bin/sh

# check if internet (not wifi) is connected (very basic)
# if nmcli command shows a route4/inet4 entry, then it indicates internet OK.
# `nmcli | grep "route4 192" | awk '{print $1}'`

while xsetroot -name " | \
`setxkbmap -query | grep layout | awk '{print $2}'` | \
`nmcli | grep "route4 192" | awk '{print $1}'` | \
`amixer get Master -M | grep Mono: | awk '{print $4}'` | \
`acpi -b | awk '{print $4}' | sed s/,//` | \
`acpi -t | awk '{print $4" "$6 }'` | \
`date +'%a %d-%b-%y | %I:%M:%S %p'`\
`#uptime | sed 's/.*,//'`\
"
do
	sleep 1
done

# TODO
# internet connection status
# input language status
# volume - mute indicator
# volume - extract specific line instead of grep mono
# volume - check if it works for headphones
# battery - charging (plugged in) status
# run separate command for each block and concantanate into 1 string at end
# emoji/symbols for various stuff
