#! /bin/sh

while xsetroot -name " | \
`amixer get Master -M | grep Mono: | awk '{print $4}'` | \
`acpi -b | awk '{print $4}' | sed s/,//` | \
`date +'%a %d-%b-%y %I:%M:%S %p'`\
`#uptime | sed 's/.*,//'`\
"
do
	sleep 1
done

# TODO
# internet connection status
# input language status
